apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: eventapp
  annotations:
    azure.workload.identity/client-id: "84919ac3-9b94-40e1-9499-b31dfd7da762"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
  namespace: eventapp
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
  namespace: eventapp
subjects:
- kind: ServiceAccount
  name: backend-sa
  namespace: eventapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backend-role




