apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: eventapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
      - name: init-js-fix
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            apk add --no-cache sed
            cd /usr/share/nginx/html
            # Find and replace the hardcoded localhost URLs
            for f in $(find . -type f -name "*.js"); do
              echo "Processing $f"
              sed -i 's|http://localhost:5000|http://72.145.47.178:5000|g' $f
            done
            echo "URL replacement completed"
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      containers:
      - name: frontend
        image: kkalteventacr.azurecr.io/frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://72.145.47.178:5000"
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: html
        emptyDir: {}
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: eventapp
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
