apiVersion: v1
kind: Namespace
metadata:
  name: eventapp
---
apiVersion: v1
kind: Secret
metadata:
  name: cosmosdb-endpoint
  namespace: eventapp
type: Opaque
data:
  endpoint: aHR0cHM6Ly9ra2FsdGV2ZW50Y29zbW9zZGIuZG9jdW1lbnRzLmF6dXJlLmNvbTo0NDMv 
---
apiVersion: v1
kind: Secret
metadata:
  name: cosmosdb-connection-string
  namespace: eventapp
type: Opaque
data:
  connection-string: QWNjb3VudEVuZHBvaW50PWh0dHBzOi8va2thbHRldmVudGNvc21vc2RiLmRvY3VtZW50cy5henVyZS5jb206NDQzLztBY2NvdW50S2V5PVBXUlR1cWVHbWhLRmdwT29Tb1FMcmRKaVE5NUF5NlhuVlprejVHQ25QS2xRQnB3VG5hYkd6TzN5MVRxaE42dk9mUjhBa2JzZ2xTaFNBQ0RiZGViY3pRPT07
---
apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
  namespace: eventapp
type: Opaque
data:
  flask-secret-key: TGlCOUtDb2tsY0lTYkQ1MXNOdkZwbkFRRXVxVFlSZVA=
